services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sakila
      TZ: "Asia/Tokyo"
    volumes:
      - ./my.cnf:/etc/mariadb/conf.d/my.cnf
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    restart: always
    